= The Duct Framework
James Reeves
{docdate}
:doctype: book
:encoding: UTF-8
:lang: en
:source-highlighter: coderay
:sectnums:
:toc: left

== Introduction

Duct is a framework for developing server-side applications in the
https://clojure.org[Clojure] programming language.

Duct does not rely on a project template; the skeleton of a Duct
application is defined by an immutable data structure. This structure
can then be queried or modified in ways that would be difficult with a
more traditional framework.

While Duct has more general use cases, it's particularly well-suited for
writing web applications. This documentation will take you through
Duct's setup and operation, using a web application as an example
project.

WARNING: This documentation assumes knowledge of Clojure. +
Some commands assume a Unix-like shell environment.

== Fundamentals

This section will introduce the fundamentals of Duct's design and
implement a minimal '`Hello World`' application. While it may be
tempting to skip ahead, a sound understanding of how to use Duct will
make later sections easier to follow.

=== Project Setup

This section will cover setting up a new Duct project. You'll first need
to ensure that the
https://clojure.org/guides/install_clojure[Clojure CLI is installed].
You can check this by running the `clojure` command.

[,shell]
----
$ clojure --version
Clojure CLI version 1.12.0.1479
----

Next, create a project directory. For the purposes of this example,
we'll call the project `tutorial`.

[,shell]
----
$ mkdir tutorial && cd tutorial
----

The Clojure CLI looks for a file called `deps.edn`. To use Duct, we need
to add the https://github.com/duct-framework/main[Duct Main] tool as a
dependency, and setup an alias to execute it.

To achieve this, create a new `deps.edn` file with the following
content:

[,clojure]
----
{:deps {org.duct-framework/main {:mvn/version "0.1.1"}}
 :aliases {:duct {:main-opts ["-m" "duct.main"]}}}
----

Duct can now be run by invoking the `:duct` alias.

[,shell]
----
$ clojure -M:duct
Usage:
	clojure -M:duct [--main | --repl]
Options:
  -c, --cider              Start an NREPL server with CIDER middleware
      --init               Create a blank duct.edn config file
  -p, --profiles PROFILES  A concatenated list of profile keys
  -n, --nrepl              Start an NREPL server
  -m, --main               Start the application
  -r, --repl               Start a command-line REPL
  -s, --show               Print out the expanded configuration and exit
  -v, --verbose            Enable verbose logging
  -h, --help               Print this help message and exit
----

We'll be using this command a lot, so it's highly recommended that you
also create an shell alias. In a POSIX shell such as Bash, this can be
done using the `alias` command.

[,shell]
----
$ alias duct="clojure -M:duct"
----

For the rest of this documentation, we'll assume that this shell alias
has been defined.

The final step of the setup process is to create a `duct.edn` file. This
contains the data structure that defines your Duct application. The
Duct Main tool has a flag to generate a minimal configuration file for
us.

[,shell]
----
$ duct --init
Created duct.edn
----

This will create a file, `duct.edn` with the content:

[,clojure]
----
{:system {}}
----

=== Hello World

As mentioned previously, Duct uses a file, `duct.edn`, to define the
structure of your application. We'll begin by adding a new component
key to the system:

[,clojure]
----
{:system
 {:tutorial.print/hello {}}}
----

If we try running Duct, it will complain about a missing namespace.

[,shell]
----
$ duct --main
✓ Initiating system...
Execution error (IllegalArgumentException) at integrant.core/eval1191$fn (core.cljc:490).
No such namespace: tutorial.print
----

Duct is searching for a definition for the component, but not finding
anything. This is unsurprising, as we haven't written any code yet.
Let's fix this.

First we'll create the directories.

[,shell]
----
mkdir -p src/tutorial
----

Then a minimal Clojure file at: `src/tutorial/print.clj`.

[,clojure]
----
(ns tutorial.print)

(defn hello [_options]
  (println "Hello World"))
----

Now if we try to run the application, we get the expected output.

[,shell]
----
$ duct --main
✓ Initiating system...
Hello World
----

Congratulations on your first Duct application!

=== The REPL

Duct has two ways of running your application: `--main` and `--repl`.

In the previous section we started the application with `--main`, which
will *initiate* the system defined in the configuration file, and *halt*
the system when the process terminates.

The REPL is an interactive development environment.

[,shell]
----
$ duct --repl
✓ Loading REPL environment...
[Repl balance] Type :repl/help for online help info
user=>
----

In the REPL environment the system will not be initiated automatically.
Instead, we use the inbuilt `(go)` function.

[,clojure]
----
user=> (go)
Hello World
:initiated
----

The REPL can be left running while source files updated. The `(reset)`
function will halt the running system, reload any modified source files,
then initiate the system again.

[,clojure]
----
user=> (reset)
:reloading (tutorial.print)
Hello World
:resumed
----

The configuration defined by `duct.edn` can be accessed with `config`,
and the running system can be accessed with `system`.

[,clojure]
----
user=> config
#:tutorial.print{:hello {}}
user=> system
#:tutorial.print{:hello nil}
----

=== Modules

A *module* groups multiple components together. Duct provides a number
of pre-written modules that implement common functionality. One of these
modules is `:duct.module/logging`.

We'll first add the dependency to `deps.edn`.

[,clojure]
----
{:deps {org.duct-framework/main {:mvn/version "0.1.1"}
        org.duct-framework/module.logging {:mvn/version "0.6.4"}}
 :aliases {:duct {:main-opts ["-m" "duct.main"]}}}
----

Then we'll add the module to the `duct.edn` configuration.

[,clojure]
----
{:system
 {:duct.module/logging {}
  :tutorial.print/hello {}}}
----

Before the components are initiated, modules are *expanded*. We can see
what this expansion looks like by using the `--show` flag. This will
print out the expanded configuration instead of initiating it.

[,shell]
----
$ duct --main --show
{:duct.logger/simple {:appenders [{:type :stdout}]}
 :tutorial.print/hello {}}
----

The logging module has been replaced with the `:duct.logger/simple`
component.

The `--show` flag also works with the `--repl` command.

[,shell]
----
$ duct --repl --show
{:duct.logger/simple
 {:appenders
  [{:type :stdout, :brief? true, :levels #{:report}}
   {:type :file, :path "logs/repl.log"}]}
 :tutorial.print/hello {}}
----

But wait a moment, why is the expansion of the configuration different
depending on how we run Duct? This is because the `--main` flag has an
implicit `:main` profile, and the `--repl` flag has an implicit `:repl`
profile.

The `:duct.module/logging` module has different behaviors depending on
which profile is active. When run with the `:main` profile, the logs
print to STDOUT, but this would be inconveniently noisy when using a
REPL. So when the `:repl` profile is active, most of the logs are sent
to a file, `logs/repl.log`.

In order to use this module, we need to connect the logger to our
'`hello`' component. This is done via a *ref*.

[,clojure]
----
{:system
 {:duct.module/logging {}
  :tutorial.print/hello {:logger #ig/ref :duct/logger}}}
----

The `#ig/ref` data reader is used to give the '`hello`' component access
to the logger. We use `:duct/logger` instead of `:duct.logger/simple`,
as keys have a logical hierarchy, and `:duct/logger` fulfils a role
similar to that of an interface or superclass.

NOTE: The '`ig`' in `#ig/var` stands for
https://github.com/weavejester/integrant[Integrant]. This is the
library that Duct relies on to turn configurations into running
applications.

Now that we've connected the components together in the configuration
file, it's time to replace the `println` function with the Duct logger.

[,clojure]
----
(ns tutorial.print
  (:require [duct.logger :as log]))

(defn hello [{:keys [logger]}]
  (log/report logger ::hello {:name "World"}))
----

The `duct.logger/report` function is used to emit a log at the `:report`
level. This is a high-priority level that should be used sparingly, as
it also prints to STDOUT when using the REPL.

You may have noticed that we've replaced the `"Hello World"` string with
a keyword and a map: `::name {:name "World"}`. This is because Duct is
opinionated about logs being data, rather than human-readable strings. A
Duct log message consists of an *event*, a qualified keyword, and a map
of *event data*, which provides additional information.

When we run the application, we can see what this produces.

[,shell]
----
$ duct --main
✓ Initiating system...
2024-11-23T18:59:14.080Z :report :tutorial.print/hello {:name "World"}
----

But when using the REPL, we get a more concise message.

[,shell]
----
user=> (go)
:initiated
:tutorial.print/hello {:name "World"}
----

=== Variables

Sometimes we want to supply options from an external source, such as an
environment variable or command line option. Duct allows variables, or
*vars*, to be defined in the `duct.edn` configuration.

Currently our application outputs the same log message each time it's
run. Let's create a configuration var to customize that behavior.

[,clojure]
----
{:vars
 {name {:arg name, :env NAME, :type :str, :default "World"
        :doc "The name of the person to greet"}}
 :system
 {:duct.module/logging {}
  :tutorial.print/hello {:logger #ig/ref :duct/logger
                         :name   #ig/var name}}}
----

Then in the source file we can add the `:name` option that the var is
attached to.

[,clojure]
----
(ns tutorial.print
  (:require [duct.logger :as log]))

(defn hello [{:keys [logger name]}]
  (log/report logger ::hello {:name name}))
----

The default ensures that the application functions the same as before.

[,shell]
----
$ duct --main
✓ Initiating system...
2024-11-23T23:53:47.069Z :report :tutorial.print/hello {:name "World"}
----

But we can now customize the behavior via a command-line flag, `--name`,
or via an environment variable, `NAME`.

[,shell]
----
$ duct --main --name=Clojurian
✓ Initiating system...
2024-11-24T04:45:19.521Z :report :tutorial.print/hello {:name "Clojurian"}

$ NAME=Clojurist duct --main
✓ Initiating system...
2024-11-24T04:45:54.211Z :report :tutorial.print/hello {:name "Clojurist"}
----

Vars are defined as a map of symbols to maps of options. The following
option keys are supported:

[horizontal]
`:arg`     :: a command-line argument to take the var's value from
`:default` :: the default value if the var is not set
`:doc`     :: a description of what the var is for
`:env`     :: an environment variable to take the var's value from
`:type`    :: a data type to coerce the var into (one of: `:str`, `:int`
              or `float`)

=== Profiles

A Duct application has some number of active profiles, which are
represented by unqualified keywords. When run via the `--main` flag, an
implicit `:main` profile is added. When run via `(go)` at the REPL, an
implicit `:repl` profile is added.

You can add additional profiles via the `--profiles` argument. Profiles
are an ordered list, with preceding profiles taking priority.

[,shell]
----
$ duct --profiles=:dev --main
----

Most of the modules that Duct provides use profiles to customize their
behavior to the environment they're being run under. We can also use the
`#ig/profile` data reader to create our own profile behavior.

Let's change our component to allow for the log level to be specified.

[,clojure]
----
(ns tutorial.print
  (:require [duct.logger :as log]))

(defn hello [{:keys [level logger name]}]
  (log/log logger level ::hello {:name name}))
----

In `duct.edn` we can use a profile to change the log level depending
on whether the application uses the `:main` or `:repl` profile.

[,clojure]
----
{:vars
 {name {:arg name, :env NAME, :type :str, :default "World"
        :doc "The name of the person to greet"}}
 :system
 {:duct.module/logging {}
  :tutorial.print/hello
  {:logger #ig/ref :duct/logger
   :level  #ig/profile {:repl :report, :main :info}
   :name   #ig/var name}}}
----

== Web Development

While Duct can be used for any server-side application, its most common
use-case is developing web applications and services. This section will
take you through writing a '`todo list`' web application in Duct.

=== Hello World Wide Web

We'll begin by creating a new project directory.

[,shell]
----
mkdir todo-app && cd todo-app
----

The first thing we'll need is a `deps.edn` file that to provide the
project dependencies. This will include Duct main and three additional
modules: logging, sql and web.

https://www.sqlite.org/index.html[SQLite] will be our database, so we'll
need the SQLite JDBC adapter as well. To give us a Clojure-friendly way
of querying the database, we'll also add
https://github.com/seancorfield/next-jdbc[next.jdbc].

.deps.edn
[,clojure]
----
{:deps {org.duct-framework/main {:mvn/version "0.1.1"}
        org.duct-framework/module.logging {:mvn/version "0.6.4"}
        org.duct-framework/module.sql {:mvn/version "0.7.0"}
        org.duct-framework/module.web {:mvn/version "0.11.0"}
        org.xerial/sqlite-jdbc {:mvn/version "3.47.0.0"}
        com.github.seancorfield/next.jdbc {:mvn/version "1.3.955"}}
 :aliases {:duct {:main-opts ["-m" "duct.main"]}}}
----

With that done, we need to ensure that the `src` directory exists. This
is the default directory Clojure uses to store source files.

[,shell]
----
$ mkdir src
----

As this is a Duct application, we'll need a `duct.edn` file. This will
contain the three modules we added to the project's dependencies.

.duct.edn
[,clojure]
----
{:system
 {:duct.module/logging {}
  :duct.module/sql {}
  :duct.module/web {}}}
----

Will this minimal configuration work? Let's find out.

[,shell]
----
duct --main
✓ Initiating system...
Execution error (ExceptionInfo) at integrant.core/unbound-vars-exception (core.cljc:343).
Unbound vars: jdbc-url

Full report at:
/tmp/clojure-14769356862243778775.edn
----

Oh dear, it looks like there's a configuration var, `jdbc-url`, that has
not been assigned a value. But where did it come from?

In this case it came from the `:duct.module/sql` module. Libraries can
add their own vars by using Integrant's keyword annotations. We can see
these new vars if we check the `--help`.

[,shell]
----
$ duct --help
Usage:
	clojure -M:duct [--main | --repl]
Options:
  -c, --cider              Start an NREPL server with CIDER middleware
      --init               Create a blank duct.edn config file
  -p, --profiles PROFILES  A concatenated list of profile keys
  -n, --nrepl              Start an NREPL server
  -m, --main               Start the application
  -r, --repl               Start a command-line REPL
  -s, --show               Print out the expanded configuration and exit
  -v, --verbose            Enable verbose logging
  -h, --help               Print this help message and exit
      --jdbc-url JDBC-URL  The JDBC database URL
      --port PORT          The HTTP server port (default: 3000)
----

At the bottom we can see that the modules have added two new options:
`--jdbc-url` and `--port`. The server port has a default value of 3000,
but there's no obvious default for a database URL, at least not one
that will suit every project.

However, we can add own own default by updating the configuration.

.duct.edn
[,clojure]
----
{:vars {jdbc-url {:default "jdbc:sqlite:todo.db"}}
 :system
 {:duct.module/logging {}
  :duct.module/sql {}
  :duct.module/web {}}}
----

Now when we run the application we get a more promising result.

[,shell]
----
$ duct --main
✓ Initiating system...
2024-11-25T02:51:08.268Z :warn :duct.migrator.ragtime/missing-file {:path "migrations.edn"}
2024-11-25T02:51:08.279Z :report :duct.server.http.jetty/starting-server {:port 3000}
----

The application warns about a missing `migrations.edn` file, but starts
up the web server. The web application should now be up and running at:
http://localhost:3000/

Visiting that URL will result in a '`404 Not Found`' error page, because
we have no routes defined. The error page will be in plaintext, because
we haven't specified what _features_ we want for our web application.

We'll fix both these issues, but before we do we should terminate the
application with Ctrl-C and start a REPL instead.

[,shell]
----
$ duct --repl
✓ Loading REPL environment...
[Repl balance] Type :repl/help for online help info
user=> (go)
:duct.server.http.jetty/starting-server {:port 3000}
:initiated
----
