= The Duct Framework
James Reeves
{docdate}
:doctype: book
:encoding: UTF-8
:lang: en
:source-highlighter: coderay
:sectnums:
:toc: left

== Introduction

Duct is a framework for developing server-side applications in the
https://clojure.org[Clojure] programming language.

Duct does not rely on a project template; the skeleton of a Duct
application is defined by an immutable data structure. This structure
can then be queried or modified in ways that would be difficult with a
more traditional framework.

While Duct has more general use cases, it's particularly well-suited for
writing web applications. This documentation will take you through
Duct's setup and operation, using a web application as an example
project.

== Setup

This section will cover setting up a new Duct project. You'll first need
to ensure that the
https://clojure.org/guides/install_clojure[Clojure CLI is installed].
You can check this by running the `clojure` command.

[,shell]
----
$ clojure --version
Clojure CLI version 1.12.0.1479
----

Next, create a project directory. For the purposes of this example,
we'll call the project `tutorial`.

[,shell]
----
$ mkdir tutorial && cd tutorial
----

The Clojure CLI looks for a file called `deps.edn`. To use Duct, we need
to add the https://github.com/duct-framework/main[Duct Main] tool as a
dependency, and setup an alias to execute it.

To achieve this, create a new `deps.edn` file with the following
content:

[,clojure]
----
{:deps {org.duct-framework/main {:mvn/version "0.1.0"}}
 :aliases {:duct {:main-opts ["-m" "duct.main"]}}}
----

Duct can now be run by invoking the `:duct` alias.

[,shell]
----
$ clojure -M:duct
Usage:
	clojure -M:duct [--main | --repl]
Options:
  -c, --cider              Start an NREPL server with CIDER middleware
      --init               Create a blank duct.edn config file
  -p, --profiles PROFILES  A concatenated list of profile keys
  -n, --nrepl              Start an NREPL server
  -m, --main               Start the application
  -r, --repl               Start a command-line REPL
  -s, --show               Print out the expanded configuration and exit
  -v, --verbose            Enable verbose logging
  -h, --help               Print this help message and exit
----

We'll be using this command a lot, so it's highly recommended that you
also create an shell alias. In a POSIX shell such as Bash, this can be
done using the `alias` command.

[,shell]
----
$ alias duct="clojure -M:duct"
----

For the rest of this documentation, we'll assume that this shell alias
has been defined.

The final step of the setup process is to create a `duct.edn` file. This
contains the data structure that defines your Duct application. The
Duct Main tool has a flag to generate a minimal configuration file for
us.

[,shell]
----
$ duct --init
Created duct.edn
----

This will create a file, `duct.edn` with the content:

[,clojure]
----
{:system {}}
----

== Fundamentals

This section will introduce the fundamentals of Duct's design and
implement a minimal '`Hello World`' application. While it may be
tempting to skip ahead, a sound understanding of how to use Duct will
make later sections easier to follow.

As mentioned previously, Duct uses a file, `duct.edn`, to define the
structure of your application. We'll begin by adding a new component
key to the system:

[,clojure]
----
{:system
 {:tutorial.print/hello {}}}
----

If we try running Duct, it will complain about a missing namespace.

[,shell]
----
$ duct --main
✓ Initiating system...
Execution error (IllegalArgumentException) at integrant.core/eval1191$fn (core.cljc:490).
No such namespace: tutorial.print
----

Duct is searching for a definition for the component, but not finding
anything. This is unsurprising, as we haven't written any code yet.
Let's fix this.

First we'll create the directories.

[,shell]
----
mkdir -p src/tutorial
----

Then a minimal Clojure file at: `src/tutorial/print.clj`.

[,clojure]
----
(ns tutorial.print)

(defn hello [_options]
  (println "Hello World"))
----

Now if we try to run the application, we get the expected output.

[,shell]
----
$ duct --main
✓ Initiating system...
Hello World
----

Congratulations on your first Duct application!
