= The Duct Framework
James Reeves
{docdate}
:doctype: book
:encoding: UTF-8
:lang: en
:source-highlighter: coderay
:sectnums:
:toc: left

== Introduction

Duct is a framework for developing server-side applications in the
https://clojure.org[Clojure] programming language.

Duct does not rely on a project template; the skeleton of a Duct
application is defined by an immutable data structure. This structure
can then be queried or modified in ways that would be difficult with a
more traditional framework.

While Duct has more general use cases, it's particularly well-suited for
writing web applications. This documentation will take you through
Duct's setup and operation, using a web application as an example
project.

WARNING: This documentation assumes knowledge of Clojure.

== Project Setup

This section will cover setting up a new Duct project. You'll first need
to ensure that the
https://clojure.org/guides/install_clojure[Clojure CLI is installed].
You can check this by running the `clojure` command.

[,shell]
----
$ clojure --version
Clojure CLI version 1.12.0.1479
----

Next, create a project directory. For the purposes of this example,
we'll call the project `tutorial`.

[,shell]
----
$ mkdir tutorial && cd tutorial
----

The Clojure CLI looks for a file called `deps.edn`. To use Duct, we need
to add the https://github.com/duct-framework/main[Duct Main] tool as a
dependency, and setup an alias to execute it.

To achieve this, create a new `deps.edn` file with the following
content:

[,clojure]
----
{:deps {org.duct-framework/main {:mvn/version "0.1.0"}}
 :aliases {:duct {:main-opts ["-m" "duct.main"]}}}
----

Duct can now be run by invoking the `:duct` alias.

[,shell]
----
$ clojure -M:duct
Usage:
	clojure -M:duct [--main | --repl]
Options:
  -c, --cider              Start an NREPL server with CIDER middleware
      --init               Create a blank duct.edn config file
  -p, --profiles PROFILES  A concatenated list of profile keys
  -n, --nrepl              Start an NREPL server
  -m, --main               Start the application
  -r, --repl               Start a command-line REPL
  -s, --show               Print out the expanded configuration and exit
  -v, --verbose            Enable verbose logging
  -h, --help               Print this help message and exit
----

We'll be using this command a lot, so it's highly recommended that you
also create an shell alias. In a POSIX shell such as Bash, this can be
done using the `alias` command.

[,shell]
----
$ alias duct="clojure -M:duct"
----

For the rest of this documentation, we'll assume that this shell alias
has been defined.

The final step of the setup process is to create a `duct.edn` file. This
contains the data structure that defines your Duct application. The
Duct Main tool has a flag to generate a minimal configuration file for
us.

[,shell]
----
$ duct --init
Created duct.edn
----

This will create a file, `duct.edn` with the content:

[,clojure]
----
{:system {}}
----

== Fundamentals

This section will introduce the fundamentals of Duct's design and
implement a minimal '`Hello World`' application. While it may be
tempting to skip ahead, a sound understanding of how to use Duct will
make later sections easier to follow.

=== First Steps

As mentioned previously, Duct uses a file, `duct.edn`, to define the
structure of your application. We'll begin by adding a new component
key to the system:

[,clojure]
----
{:system
 {:tutorial.print/hello {}}}
----

If we try running Duct, it will complain about a missing namespace.

[,shell]
----
$ duct --main
✓ Initiating system...
Execution error (IllegalArgumentException) at integrant.core/eval1191$fn (core.cljc:490).
No such namespace: tutorial.print
----

Duct is searching for a definition for the component, but not finding
anything. This is unsurprising, as we haven't written any code yet.
Let's fix this.

First we'll create the directories.

[,shell]
----
mkdir -p src/tutorial
----

Then a minimal Clojure file at: `src/tutorial/print.clj`.

[,clojure]
----
(ns tutorial.print)

(defn hello [_options]
  (println "Hello World"))
----

Now if we try to run the application, we get the expected output.

[,shell]
----
$ duct --main
✓ Initiating system...
Hello World
----

Congratulations on your first Duct application!

=== The REPL

Duct has two ways of running your application: `--main` and `--repl`.

In the previous section we started the application with `--main`, which
will *initiate* the system defined in the configuration file, and *halt*
the system when the process terminates.

The REPL is an interactive development environment.

[,shell]
----
$ duct --repl
✓ Loading REPL environment...
[Repl balance] Type :repl/help for online help info
user=>
----

In the REPL environment the system will not be initiated automatically.
Instead, we use the inbuilt `(go)` function.

[,clojure]
----
user=> (go)
Hello World
:initiated
----

The REPL can be left running while source files updated. The `(reset)`
function will halt the running system, reload any modified source files,
then initiate the system again.

[,clojure]
----
user=> (reset)
:reloading (tutorial.print)
Hello World
:resumed
----

The configuration defined by `duct.edn` can be accessed with `config`,
and the running system can be accessed with `system`.

[,clojure]
----
user=> config
#:tutorial.print{:hello {}}
user=> system
#:tutorial.print{:hello nil}
----

=== Modules

A *module* groups multiple components together. Duct provides a number
of pre-written modules that implement common functionality. One of these
modules is `:duct.module/logging`.

We'll first add the dependency to `deps.edn`.

[,clojure]
----
{:deps {org.duct-framework/main {:mvn/version "0.1.0"}
        org.duct-framework/module.logging {:mvn/version "0.6.4"}}
 :aliases {:duct {:main-opts ["-m" "duct.main"]}}}
----

Then we'll add the module to the `duct.edn` configuration.

[,clojure]
----
{:system
 {:duct.module/logging {}
  :tutorial.print/hello {}}}
----

Before the components are initiated, modules are *expanded*. We can see
what this expansion looks like by using the `--show` flag. This will
print out the expanded configuration instead of initiating it.

[,shell]
----
$ duct --main --show
{:duct.logger/simple {:appenders [{:type :stdout}]}
 :tutorial.print/hello {}}
----

The logging module has been replaced with the `:duct.logger/simple`
component.

The `--show` flag also works with the `--repl` command.

[,shell]
----
$ duct --repl --show
{:duct.logger/simple
 {:appenders
  [{:type :stdout, :brief? true, :levels #{:report}}
   {:type :file, :path "logs/repl.log"}]}
 :tutorial.print/hello {}}
----

But wait a moment, why is the expansion of the configuration different
depending on how we run Duct? This is because the `--main` flag has an
implicit `:main` profile, and the `--repl` flag has an implicit `:repl`
profile.

The `:duct.module/logging` module has different behaviors depending on
which profile is active. When run with the `:main` profile, the logs
print to STDOUT, but this would be inconveniently noisy when using a
REPL. So when the `:repl` profile is active, most of the logs are sent
to a file, `logs/repl.log`.

In order to use this module, we need to connect the logger to our
'`hello`' component. This is done via a *ref*.

[,clojure]
----
{:system
 {:duct.module/logging {}
  :tutorial.print/hello {:logger #ig/ref :duct/logger}}}
----

The `#ig/ref` data reader is used to give the '`hello`' component access
to the logger. We use `:duct/logger` instead of `:duct.logger/simple`,
as keys have a logical hierarchy, and `:duct/logger` fulfils a role
similar to that of an interface or superclass.

NOTE: The '`ig`' in `#ig/var` stands for _Integrant_. This is the
library that Duct relies on to turn configurations into running
applications.

Now that we've connected the components together in the configuration
file, it's time to replace the `println` function with the Duct logger.

[,clojure]
----
(ns tutorial.print
  (:require [duct.logger :as log]))

(defn hello [{:keys [logger]}]
  (log/report logger ::hello {:name "World"}))
----

The `duct.logger/report` function is used to emit a log at the `:report`
level. This is a high-priority level that should be used sparingly, as
it also prints to STDOUT when using the REPL.

You may have noticed that we've replaced the `"Hello World"` string with
a keyword and a map: `::name {:name "World"}`. This is because Duct is
opinionated about logs being data, rather than human-readable strings. A
Duct log message consists of an *event*, a qualified keyword, and a map
of *event data*, which provides additional information.

When we run the application, we can see what this produces.

[,shell]
----
$ duct --main
✓ Initiating system...
2024-11-23T18:59:14.080Z :report :tutorial.print/hello {:name "World"}
----

When using the REPL, we get a more concise message.

[,shell]
----
user=> (go)
:initiated
:tutorial.print/hello {:name "World"}
----
