name: Deploy ASCIIDoc site to Pages
on:
  push:
    branches: ["master"]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    name: asciidoctor -D build index.adoc
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          bb: latest
      - name: Install AsciiDoctor
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: asciidoctor pandoc
          version: 1.0
      - name: Build AsciiDoc
        id: adocbuild
        run: bb build
      - name: Print execution time
        run: echo "Time ${{ steps.adocbuild.outputs.time }}"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
